
INSERT INTO BURGERS_DB.BURGERS
(BURGER_NAME, DEVOURED)
VALUES('Burger 1',false);

INSERT INTO BURGERS_DB.BURGERS
(BURGER_NAME, DEVOURED)
VALUES('Burger 2', true);

INSERT INTO BURGERS_DB.BURGERS
(BURGER_NAME, DEVOURED)
VALUES('Burger Red', true);

INSERT INTO BURGERS_DB.BURGERS
(BURGER_NAME, DEVOURED)
VALUES('Burger Blue', false);

INSERT INTO BURGERS_DB.BURGERS
(BURGER_NAME, DEVOURED)
VALUES('Burger Hulk', true);
